### ISSUE TITLE
bcos2版本的生成出来包部分是不兼容的

### ISSUE THREAD

**Issue by wuhua666** [FISCO-BCOS/code-generator#10]
bcos2环境生成出来的java代码依赖了一个sdk不存在的org.fisco.bcos.sdk.codec.Utils.typeMap包。

**Comment by kyonRay** [comment]
请问是在2.+版本的sdk环境下编译错误的吗？能否给出具体的步骤？

**Comment by kyonRay** [comment]
感谢提出问题，这里应该是有全局替换时错误操作导致的问题，在最新版本将会修复。:)

**Comment by kyonRay** [comment]
#12 这一个PR修复了这个问题。
