### ISSUE TITLE
ContractWrapper.extractStructs方法中，extractsNested功能没有了

### ISSUE THREAD

**Issue by arc0035** [FISCO-BCOS/code-generator#5]
我在脚手架适配3.0稳定版过程中，发现KVTable.sol仅能生成Entry结构体，不再能生成KVField结构体。

究其原因，KVField结构体是嵌套在Entry结构体中，不会直接出现在函数输入中。

在rc3的逻辑中，ContractWrapper.extractStructs不仅会查找函数输入里的结构体，还会递归地查找结构体内部包含的其他结构体，对应代码体现在这里：
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/6778136/192945085-5d63a065-fc20-4663-9f39-c9bd6c2c9887.png">

但是在3.0.0稳定版中，这部分代码砍掉了：
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/6778136/192945151-4323b96d-862f-4b21-8c37-940113a401f8.png">

还是希望把这个功能加上

**Comment by kyonRay** [comment]
感谢提出issue，这个问题会在最新的版本支持。:)

**Comment by kyonRay** [comment]
#12 这一个PR修复了这个问题
